version: '3.9'
services:

  ocsprey:
    build:
      context: .
      dockerfile: Dockerfile
      target: ocsprey
    command:
      - server
      - --config=testdata/config.yml
      - --port=8888
      - --log-level=debug
    ports:
      - "8888:8888"
    volumes:
      - ./testdata:/opt/ocsprey/testdata
    working_dir: /opt/ocsprey

  postgres:
    image: postgres:15.1
    environment:
    - POSTGRES_PASSWORD=testbed
    - POSTGRES_USER=ocsprey
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  cassandra:
    image: cassandra:3.11.14
    ports:
      - "7000:7000"
    volumes:
      - cassandra:/opt/cassandra/data/

  redis:
    image: redis:7.0.8
    command: >
      --requirepass testbed
    volumes:
    - redis:/data

volumes:
  postgres:
  redis:
  cassandra:
